# Generated by Django 5.2.8 on 2025-11-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
