# Generated by Django 5.2.8 on 2025-11-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_cover_url_story_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user_uuid',
            new_name='client_uuid',
        ),
    ]
