# Generated by Django 5.2.8 on 2025-11-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='style',
        ),
        migrations.AddField(
            model_name='scene',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
