# Generated by Django 5.2.8 on 2025-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_remove_scene_style_scene_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
