# Generated by Django 5.2.8 on 2025-11-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
